// ----------------------------------------------------------------------
// <copyright file="EnumWithValues.cs" company="Xavier Solau">
// Copyright © 2021 Xavier Solau.
// Licensed under the MIT license.
// See LICENSE file in the project root for full license information.
// </copyright>
// ----------------------------------------------------------------------

namespace SoloX.GeneratorTools.Core.CSharp.UTest.Resources.Model.Basic.Enums
{
    public enum EnumWithValues
    {
        Unknown = 0,
        AD = 1,
        AE = 2,
        AL = 3,
        AM = 4,
        AR = 5,
        AT = 6,
        AU = 7,
        AZ = 8,
        BA = 9,
        BE = 10,
        BG = 11,
        BH = 12,
        BO = 13,
        BR = 14,
        BY = 15,
        CA = 16,
        CH = 17,
        CL = 18,
        CN = 19,
        CO = 20,
        CR = 21,
        CU = 22,
        CY = 23,
        CZ = 24,
        DE = 25,
        DK = 26,
        DO = 27,
        EC = 28,
        EE = 29,
        ES = 30,
        FI = 31,
        FO = 32,
        FR = 33,
        GB = 34,
        GE = 35,
        GR = 36,
        GT = 37,
        HK = 38,
        HR = 39,
        HU = 40,
        ID = 41,
        IE = 42,
        IL = 43,
        IN = 44,
        IS = 45,
        IT = 46,
        JP = 47,
        KR = 48,
        KZ = 49,
        LT = 50,
        LU = 51,
        LV = 52,
        MC = 53,
        MD = 54,
        ME = 55,
        MK = 56,
        MT = 57,
        MU = 58,
        MX = 59,
        MY = 60,
        NG = 61,
        NL = 62,
        NO = 63,
        NZ = 64,
        PE = 65,
        PH = 66,
        PK = 67,
        PL = 68,
        PT = 69,
        PY = 70,
        RO = 71,
        RS = 72,
        RU = 73,
        SE = 74,
        SI = 75,
        SK = 76,
        SM = 77,
        SV = 78,
        TH = 79,
        TR = 80,
        TW = 81,
        UA = 82,
        US = 83,
        UY = 84,
        UZ = 85,
        VE = 86,
        ZA = 87
    }
}
