name: Build - PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: xaviersolau/devops-workflows/.github/workflows/build-dotnet.yml@v1.1.0
    with:
      test-projects: >
        [
          "src/tests/SoloX.GeneratorTools.Core.UTest",
          "src/tests/SoloX.GeneratorTools.Core.CSharp.UTest",
          "src/tests/SoloX.GeneratorTools.Core.CSharp.ITest",
          "src/tools.tests/SoloX.GeneratorTools.Generator.ITest"
        ]
